import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Contracts.module.css'


export default function Contracts() {
    return (
        <>
        <Head>
            <title>Dragon Toon</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
            <h2>Contract - April 24, 2023</h2>
            <br />
            <br />
            <p>3 party contract - 1, 2, 3</p>
            <br />
            <br />
            <Image
                src="/ethereum-contract.jpeg"
                width={1200}
                height={720}
                alt="Ethereum contract"
            />
            <br />
            <br />
            <p>To be finished by December 2023.</p>
        </main>
        </>
    )
}