import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'


const inter = Inter({ subsets: ['latin'] })

export default function Contact() {
  return (
    <>
      <Head>
        <title>Dragon Toon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <h1>Ender&apos;s Game themed hacker house</h1>
        <h2>A house filled with AI enthusiasts</h2>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/dragon-toon.png"
            alt="Next.js Logo"
            width={512}
            height={512}
            priority
          />
        </div>
        
        <p>Reach out at info@agilend.net</p>

      </main>
    </>
  )
}
